# Generated by Django 5.2.12 on 2026-03-15 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
