# Generated by Django 5.2.12 on 2026-03-15 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default=datetime.datetime(2026, 3, 15, 16, 13, 52, 244442, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
