# Generated by Django 5.2.12 on 2026-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Активна'), ('maintenance', 'На обслуживании'), ('closed', 'Закрыта')], default='active', max_length=100)),
                ('type', models.CharField(choices=[('lecture', 'Лекционная'), ('seminar', 'Семинарская'), ('lab', 'Лаборатория'), ('conference', 'Конференц-зал'), ('hall', 'Актовый зал')], default='lecture', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
    ]
