# Generated by Django 5.2.12 on 2026-08-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('projector', 'Проектор'), ('microphone', 'Микрофон'), ('laptop', 'Ноутбук'), ('screen', 'Экран'), ('camera', 'Веб-камера')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('maintenance', 'На обслуживании'), ('written_off', 'Списано')], default='active', max_length=20)),
                ('is_stationary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
