# Generated by Django 5.2.12 on 2026-03-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('projector', 'Проектор'), ('microphone', 'Микрофон'), ('laptop', 'Ноутбук'), ('screen', 'Экран'), ('camera', 'Веб-камера')], max_length=100)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Зарезервировано'), ('maintenance', 'На обслуживании'), ('written_off', 'Списано')], default='available', max_length=100)),
                ('is_stationary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Оборудование',
            },
        ),
    ]
