# Generated by Django 5.2.12 on 2026-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('maintenance', 'На обслуживании'), ('written_off', 'Списано')], default='available', max_length=20),
        ),
    ]
