# Generated by Django 5.2.12 on 2026-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('maintenance', 'На обслуживании'), ('written_off', 'Списано')], default='active', max_length=20),
        ),
    ]
