# Generated by Django 5.2.12 on 2026-03-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_and_more'),
        ('rooms', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='rooms.room'),
        ),
    ]
