# Generated by Django 5.2.12 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'ожидает'), ('approved', 'одобрено'), ('rejected', 'отклонено')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Согласование заявки',
                'verbose_name_plural': 'Согласования заявок',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практическое занятие'), ('state_exam', 'Государственный экзамен'), ('thesis_defense', 'Защита ВКР'), ('scientific_seminar', 'Научный семинар'), ('conference', 'Конференция'), ('organizational_meeting', 'Организационное собрание')], default='lecture', max_length=30)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('participants', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'создана'), ('pending', 'на согласовании'), ('approved', 'одобрена'), ('rejected', 'отклонена'), ('completed', 'завершена'), ('canceled', 'отменена')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
