# Generated by Django 5.2.12 on 2026-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Групповая заявка',
                'verbose_name_plural': 'Групповые заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практическое занятие'), ('state_exam', 'Государственный экзамен'), ('thesis_defense', 'Защита ВКР'), ('scientific_seminar', 'Научный семинар'), ('conference', 'Конференция'), ('organizational_meeting', 'Организационное собрание')], default='lecture', max_length=30)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('participants', models.IntegerField(default=60)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'создана'), ('pending', 'на согласовании'), ('approved', 'одобрена'), ('rejected', 'отклонена'), ('completed', 'завершена'), ('canceled', 'отменена')], default='created', max_length=20)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_source', models.CharField(choices=[('system', 'система'), ('manual', 'вручную')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='bookings', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
            },
        ),
    ]
