# Generated by Django 5.2.12 on 2026-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('equipment', '0002_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='equipment.equipment'),
        ),
    ]
