# Generated by Django 5.2.12 on 2026-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
