# Generated by Django 5.2.12 on 2026-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'одобрена'), ('in_process', 'в процессе'), ('rejected', 'отклонена')], max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Согласование заявки',
                'verbose_name_plural': 'Согласования заявок',
            },
        ),
    ]
