# Generated by Django 5.2.12 on 2026-04-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0006_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'одобрено'), ('requires_correction', 'требует правок'), ('rejected', 'отклонено')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Согласование заявки',
                'verbose_name_plural': 'Согласования заявок',
            },
        ),
    ]
