# Generated by Django 5.2.12 on 2026-04-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('booking', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('approved', 'одобрено'), ('in_process', 'в процессе'), ('rejected', 'отклонено')], max_length=20),
        ),
    ]
