# Generated by Django 5.2.12 on 2026-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_alter_approval_booking_alter_approval_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='comment',
        ),
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('approved', 'одобрена'), ('in_process', 'в процессе'), ('rejected', 'отклонена')], max_length=20),
        ),
    ]
