# Generated by Django 5.2.12 on 2026-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('booking_status', 'Изменение статуса заявки'), ('comment_added', 'Новый комментарий')], default='comment_added', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
